### PR TITLE
Added RootViewGettable

### PR DESCRIPTION
**Pull request by artemch**
Added RootViewGettable protocol and protocol extension.
Added tests for RootViewGettable protocol.
Added example.
Added cocoapods and carthage support.

### CODE REVIEW

**Comment by trimmurrti** [comment]
Please, make a file structure similar to IDPCastable.
Please, add the summary and readme
Please, use IDPCastable for type casting
let rootView is unneeded in ViewController, as the property is used only once.

**Comment by artemch** [comment]
> Please, use IDPCastable for type casting

IDPCastable dependency break Carthage support on IDPRootViewGettable, so we should first add Carthage support to IDPCastable.

**Comment by artemch** [comment]
Carthage does not work properly on IDPRootViewGettable, so I break it and add IDPCastable for type casting.

**Comment by artemch** [comment]
>Please, make a file structure similar to IDPCastable.
>Please, add the summary and readme
>Please, use IDPCastable for type casting
>let rootView is unneeded in ViewController, as the property is used only once.

fixed

**Comment by artemch** [comment]
Update example.

**Pull request merged**
